// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/proto/adele.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdeleService_Connect_FullMethodName = "/adele.AdeleService/Connect"
)

// AdeleServiceClient is the client API for AdeleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdeleServiceClient interface {
	// 双向流 - 主通信通道
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
}

type adeleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdeleServiceClient(cc grpc.ClientConnInterface) AdeleServiceClient {
	return &adeleServiceClient{cc}
}

func (c *adeleServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AdeleService_ServiceDesc.Streams[0], AdeleService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdeleService_ConnectClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

// AdeleServiceServer is the server API for AdeleService service.
// All implementations must embed UnimplementedAdeleServiceServer
// for forward compatibility.
type AdeleServiceServer interface {
	// 双向流 - 主通信通道
	Connect(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	mustEmbedUnimplementedAdeleServiceServer()
}

// UnimplementedAdeleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdeleServiceServer struct{}

func (UnimplementedAdeleServiceServer) Connect(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAdeleServiceServer) mustEmbedUnimplementedAdeleServiceServer() {}
func (UnimplementedAdeleServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdeleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdeleServiceServer will
// result in compilation errors.
type UnsafeAdeleServiceServer interface {
	mustEmbedUnimplementedAdeleServiceServer()
}

func RegisterAdeleServiceServer(s grpc.ServiceRegistrar, srv AdeleServiceServer) {
	// If the following call panics, it indicates UnimplementedAdeleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdeleService_ServiceDesc, srv)
}

func _AdeleService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AdeleServiceServer).Connect(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdeleService_ConnectServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

// AdeleService_ServiceDesc is the grpc.ServiceDesc for AdeleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdeleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "adele.AdeleService",
	HandlerType: (*AdeleServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AdeleService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/adele.proto",
}
