// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/adele.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`    // 客户端唯一标识
	LocalAddr     string                 `protobuf:"bytes,2,opt,name=local_addr,json=localAddr,proto3" json:"local_addr,omitempty"` // 本地HTTP服务地址，如 localhost:3000
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_adele_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_adele_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_adele_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RegisterRequest) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 服务端分配的会话ID
	ProxyAddr     string                 `protobuf:"bytes,2,opt,name=proxy_addr,json=proxyAddr,proto3" json:"proxy_addr,omitempty"` // 分配的代理访问地址，如 server:8081
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_adele_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_adele_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_adele_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterResponse) GetProxyAddr() string {
	if x != nil {
		return x.ProxyAddr
	}
	return ""
}

type HTTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                                                      // 请求唯一ID
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`                                                                             // GET, POST, etc.
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`                                                                                 // 请求路径
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 请求头
	Body          []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`                                                                                 // 请求体
	Query         string                 `protobuf:"bytes,6,opt,name=query,proto3" json:"query,omitempty"`                                                                               // 查询参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPRequest) Reset() {
	*x = HTTPRequest{}
	mi := &file_api_proto_adele_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPRequest) ProtoMessage() {}

func (x *HTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_adele_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPRequest.ProtoReflect.Descriptor instead.
func (*HTTPRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_adele_proto_rawDescGZIP(), []int{2}
}

func (x *HTTPRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HTTPRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HTTPRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HTTPRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HTTPRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type HTTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                                                      // 对应的请求ID
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`                                                  // HTTP状态码
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 响应头
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`                                                                                 // 响应体
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPResponse) Reset() {
	*x = HTTPResponse{}
	mi := &file_api_proto_adele_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPResponse) ProtoMessage() {}

func (x *HTTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_adele_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPResponse.ProtoReflect.Descriptor instead.
func (*HTTPResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_adele_proto_rawDescGZIP(), []int{3}
}

func (x *HTTPResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HTTPResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HTTPResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_adele_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_adele_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_adele_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_adele_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_adele_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_adele_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Register
	//	*ClientMessage_Heartbeat
	//	*ClientMessage_HttpResponse
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_api_proto_adele_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_adele_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_adele_proto_rawDescGZIP(), []int{6}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *ClientMessage) GetHeartbeat() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ClientMessage) GetHttpResponse() *HTTPResponse {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_HttpResponse); ok {
			return x.HttpResponse
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type ClientMessage_Heartbeat struct {
	Heartbeat *HeartbeatRequest `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type ClientMessage_HttpResponse struct {
	HttpResponse *HTTPResponse `protobuf:"bytes,3,opt,name=http_response,json=httpResponse,proto3,oneof"`
}

func (*ClientMessage_Register) isClientMessage_Payload() {}

func (*ClientMessage_Heartbeat) isClientMessage_Payload() {}

func (*ClientMessage_HttpResponse) isClientMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Register
	//	*ServerMessage_Heartbeat
	//	*ServerMessage_HttpRequest
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_api_proto_adele_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_adele_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_adele_proto_rawDescGZIP(), []int{7}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetRegister() *RegisterResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *ServerMessage) GetHeartbeat() *HeartbeatResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ServerMessage) GetHttpRequest() *HTTPRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_HttpRequest); ok {
			return x.HttpRequest
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Register struct {
	Register *RegisterResponse `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type ServerMessage_Heartbeat struct {
	Heartbeat *HeartbeatResponse `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type ServerMessage_HttpRequest struct {
	HttpRequest *HTTPRequest `protobuf:"bytes,3,opt,name=http_request,json=httpRequest,proto3,oneof"`
}

func (*ServerMessage_Register) isServerMessage_Payload() {}

func (*ServerMessage_Heartbeat) isServerMessage_Payload() {}

func (*ServerMessage_HttpRequest) isServerMessage_Payload() {}

var File_api_proto_adele_proto protoreflect.FileDescriptor

const file_api_proto_adele_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/adele.proto\x12\x05adele\"M\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"local_addr\x18\x02 \x01(\tR\tlocalAddr\"P\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"proxy_addr\x18\x02 \x01(\tR\tproxyAddr\"\xf9\x01\n" +
	"\vHTTPRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x129\n" +
	"\aheaders\x18\x04 \x03(\v2\x1f.adele.HTTPRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x12\x14\n" +
	"\x05query\x18\x06 \x01(\tR\x05query\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xda\x01\n" +
	"\fHTTPResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12:\n" +
	"\aheaders\x18\x03 \x03(\v2 .adele.HTTPResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"4\n" +
	"\x11HeartbeatResponse\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime\"\xc5\x01\n" +
	"\rClientMessage\x124\n" +
	"\bregister\x18\x01 \x01(\v2\x16.adele.RegisterRequestH\x00R\bregister\x127\n" +
	"\theartbeat\x18\x02 \x01(\v2\x17.adele.HeartbeatRequestH\x00R\theartbeat\x12:\n" +
	"\rhttp_response\x18\x03 \x01(\v2\x13.adele.HTTPResponseH\x00R\fhttpResponseB\t\n" +
	"\apayload\"\xc4\x01\n" +
	"\rServerMessage\x125\n" +
	"\bregister\x18\x01 \x01(\v2\x17.adele.RegisterResponseH\x00R\bregister\x128\n" +
	"\theartbeat\x18\x02 \x01(\v2\x18.adele.HeartbeatResponseH\x00R\theartbeat\x127\n" +
	"\fhttp_request\x18\x03 \x01(\v2\x12.adele.HTTPRequestH\x00R\vhttpRequestB\t\n" +
	"\apayload2I\n" +
	"\fAdeleService\x129\n" +
	"\aConnect\x12\x14.adele.ClientMessage\x1a\x14.adele.ServerMessage(\x010\x01B'Z%github.com/rcpqc/adele/internal/protob\x06proto3"

var (
	file_api_proto_adele_proto_rawDescOnce sync.Once
	file_api_proto_adele_proto_rawDescData []byte
)

func file_api_proto_adele_proto_rawDescGZIP() []byte {
	file_api_proto_adele_proto_rawDescOnce.Do(func() {
		file_api_proto_adele_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_adele_proto_rawDesc), len(file_api_proto_adele_proto_rawDesc)))
	})
	return file_api_proto_adele_proto_rawDescData
}

var file_api_proto_adele_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_adele_proto_goTypes = []any{
	(*RegisterRequest)(nil),   // 0: adele.RegisterRequest
	(*RegisterResponse)(nil),  // 1: adele.RegisterResponse
	(*HTTPRequest)(nil),       // 2: adele.HTTPRequest
	(*HTTPResponse)(nil),      // 3: adele.HTTPResponse
	(*HeartbeatRequest)(nil),  // 4: adele.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 5: adele.HeartbeatResponse
	(*ClientMessage)(nil),     // 6: adele.ClientMessage
	(*ServerMessage)(nil),     // 7: adele.ServerMessage
	nil,                       // 8: adele.HTTPRequest.HeadersEntry
	nil,                       // 9: adele.HTTPResponse.HeadersEntry
}
var file_api_proto_adele_proto_depIdxs = []int32{
	8, // 0: adele.HTTPRequest.headers:type_name -> adele.HTTPRequest.HeadersEntry
	9, // 1: adele.HTTPResponse.headers:type_name -> adele.HTTPResponse.HeadersEntry
	0, // 2: adele.ClientMessage.register:type_name -> adele.RegisterRequest
	4, // 3: adele.ClientMessage.heartbeat:type_name -> adele.HeartbeatRequest
	3, // 4: adele.ClientMessage.http_response:type_name -> adele.HTTPResponse
	1, // 5: adele.ServerMessage.register:type_name -> adele.RegisterResponse
	5, // 6: adele.ServerMessage.heartbeat:type_name -> adele.HeartbeatResponse
	2, // 7: adele.ServerMessage.http_request:type_name -> adele.HTTPRequest
	6, // 8: adele.AdeleService.Connect:input_type -> adele.ClientMessage
	7, // 9: adele.AdeleService.Connect:output_type -> adele.ServerMessage
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_adele_proto_init() }
func file_api_proto_adele_proto_init() {
	if File_api_proto_adele_proto != nil {
		return
	}
	file_api_proto_adele_proto_msgTypes[6].OneofWrappers = []any{
		(*ClientMessage_Register)(nil),
		(*ClientMessage_Heartbeat)(nil),
		(*ClientMessage_HttpResponse)(nil),
	}
	file_api_proto_adele_proto_msgTypes[7].OneofWrappers = []any{
		(*ServerMessage_Register)(nil),
		(*ServerMessage_Heartbeat)(nil),
		(*ServerMessage_HttpRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_adele_proto_rawDesc), len(file_api_proto_adele_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_adele_proto_goTypes,
		DependencyIndexes: file_api_proto_adele_proto_depIdxs,
		MessageInfos:      file_api_proto_adele_proto_msgTypes,
	}.Build()
	File_api_proto_adele_proto = out.File
	file_api_proto_adele_proto_goTypes = nil
	file_api_proto_adele_proto_depIdxs = nil
}
